dependencies:
  config:
    - field.field.user.user.layout_builder__layout
    - field.field.user.user.layout_selection
content:
  layout_selection:
    type: options_select
    weight: 4
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  contact: true
  langcode: true
  layout_builder__layout: true
  timezone: true
