dependencies:
  config:
    - entity_browser.browser.image_browser
    - field.field.node.article.field_author
    - field.field.node.article.field_content
    - field.field.node.article.field_meta_tags
    - field.field.node.article.field_short_title
    - field.field.node.article.field_social_sharing
    - field.field.node.article.field_subhead
    - field.field.node.article.field_summary
    - field.field.node.article.field_tags
    - field.field.node.article.field_thumbnail
    - field.field.node.article.field_yoast_seo
    - node.type.article
    - workflows.workflow.default
  module:
    - autocomplete_deluxe
    - content_moderation
    - entity_browser
    - field_group
    - length_indicator
    - metatag
    - paragraphs
    - paragraphs_ee
    - paragraphs_features
    - path
    - scheduler
    - social_media
    - yoast_seo
content:
  field_content:
    type: paragraphs
    weight: 9
    settings:
      title: Paragraph
      title_plural: Paragraphs
      edit_mode: closed
      closed_mode: summary
      autocollapse: none
      closed_mode_threshold: 0
      add_mode: modal
      form_display_mode: default
      default_paragraph_type: _none
      features:
        add_above: add_above
        collapse_edit_all: collapse_edit_all
        duplicate: duplicate
    third_party_settings:
      paragraphs_features:
        delete_confirmation: true
        add_in_between: true
        split_text: true
        show_drag_and_drop: true
      paragraphs_ee:
        paragraphs_ee:
          dialog_style: tiles
          easy_access_count: '3'
          dialog_off_canvas: false
    region: content
  field_meta_tags:
    weight: 121
    settings:
      sidebar: true
      async_groups:
        advanced: advanced
        schema_article: schema_article
        basic: '0'
    third_party_settings: {  }
    type: metatag_async
    region: content
