core.entity_form_display.node.article.default:
  expected_config:
    content:
      field_meta_tags:
        weight: 121
        settings: {  }
        third_party_settings: {  }
        type: metatag_firehose
        region: content
  update_actions:
    change:
      content:
        field_meta_tags:
          weight: 121
          settings:
            sidebar: true
          third_party_settings: {  }
          type: metatag_async
          region: content
