core.entity_form_display.node.article.default:
  expected_config:
    content:
      field_meta_tags:
        region: content
  update_actions:
    change:
      content:
        field_meta_tags:
          weight: 121
          settings:
            sidebar: true
            async_groups:
              advanced: advanced
              schema_article: schema_article
              basic: '0'
          third_party_settings: {  }
          type: metatag_async
          region: content
