_core:
  default_config_hash: fFtMJuqkP65BjEBqTnAa-5fVJMy3cUCpJRv0FwXuDcE
langcode: en-gb
enabled_section_storages:
  - defaults
  - overrides
use_modal: true
auto_added_reusable_block_content_bundles: {  }
